### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.mvel2.util.ParseTools

### ISSUE THREAD

**Issue by amurashkin17** [satyagraha/gfm_viewer#95]
In the recent Eclipse version 2020-09, the plugin is not working at all. 

Every time a markdown file is being saved, a pop-up window appears with a message similar to the one below
 
```
An internal error occurred during: "Transforming: lab6-submit.md".
Could not initialize class org.mvel2.util.ParseTools
```

New markdown files (created after the Eclipse update) can not be previewed at all. In the case of old markdown files created before the Eclipse update but changed since, the preview window shows old markdown (probably, from the cache). 

The exception thrown complains that class `org.mvel2.util.ParseTools` does not exist. I have checked that ParseTools.class exists in **ext-deps-2.0.1.jar**

```
./configuration/org.eclipse.osgi/3/0/.cp/lib/code.satyagraha.gfm.viewer.ext-deps-2.0.1.jar
...
    42451  02-04-2013 17:44   org/mvel2/util/ParseTools.class
...
```

Here are some details.

```
eclipse.buildId=4.17.0.I20200902-1800
java.version=15
java.vendor=Red Hat, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
Framework arguments:  -product org.eclipse.epp.package.javascript.product
Command-line arguments:  -data file:/home/xxx/Workspace/Sawtooth/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.javascript.product

org.eclipse.core.jobs
Error
Fri Nov 20 13:39:55 CST 2020
An internal error occurred during: "Transforming: README.md".

java.lang.NoClassDefFoundError: Could not initialize class org.mvel2.util.ParseTools
	at org.mvel2.templates.TemplateCompiler.captureOrbToken(TemplateCompiler.java:305)
	at org.mvel2.templates.TemplateCompiler.compileFrom(TemplateCompiler.java:114)
	at org.mvel2.templates.TemplateCompiler.compile(TemplateCompiler.java:82)
	at org.mvel2.templates.TemplateCompiler.compileTemplate(TemplateCompiler.java:348)
	at code.satyagraha.gfm.support.impl.TransformerDefault.transformMarkdownFile(TransformerDefault.java:83)
	at code.satyagraha.gfm.ui.impl.SchedulerDefault$2.run(SchedulerDefault.java:62)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by ah1508** [comment]
Same problem with an earlier version of Eclipse (2020-03). It is more likely due to java version, for me it started to crash after I upgraded Java (from 11 to 15).

**Comment by 3rdstage** [comment]
Same problem for my case was disappeared just after JDK upgrade from 11 to 17.  I' m using Eclipse 4.12 (2019-06) and GFM viewer 2.0.1
